"""Shared utilities for the cyber-control tutorial repository.

The package keeps reusable mechanics in one place while each repository keeps
its own tutorial scripts and narrative.  Public modules stay small:

- :mod:`cybercontrol.numerics` for projections and ODE integration.
- :mod:`cybercontrol.models` for malware/hybrid dynamics and jump maps.
- :mod:`cybercontrol.heterogeneity` for scalar-or-array parameter profiles.
- :mod:`cybercontrol.network_models` for node-level SIPS graph models.
- :mod:`cybercontrol.torch_utils` for optional PyTorch helper blocks.
- :mod:`cybercontrol.io` for reproducible outputs.
- :mod:`cybercontrol.plotting` for guide and publication figure helpers.
- :mod:`cybercontrol.diagnostics` for training-diagnostic terms and captions.
"""

from .numerics import (
    as_time_function,
    project_box,
    project_compartments,
    project_simplex,
    project_simplex3,
    rk4_integrate,
    rk4_step,
    solve_ode_grid,
    trapezoid,
    trapezoid_integral,
)
from .models import (
    HybridParams,
    MalwareParams,
    controlled_sir_rhs,
    hybrid_rhs,
    isolation_jump,
)
from .network_models import (
    NodeSIPSParams,
    community_correlated_node_sips_params,
    contiguous_community_index,
    degree_correlated_node_sips_params,
    graph_pressure_numpy,
    graph_pressure_torch,
    homogeneous_node_sips_params,
    node_sips_rhs_numpy,
    node_sips_rhs_torch,
    node_sips_transition_rates,
    normalize_adjacency,
    sample_node_sips_step,
    seeded_lognormal_node_sips_params,
)
from .heterogeneity import (
    DegreeSISParams,
    NodeSISParams,
    ResolvedDegreeSISParams,
    ResolvedNodeSISParams,
    ResolvedNodeSIPSParams,
    assortative_degree_mixing,
    degree_correlated_node_sis_params,
    degree_correlated_sis_params,
    degree_sis_force,
    degree_sis_jacobian,
    degree_sis_rhs,
    finite_difference_jacobian,
    neutral_degree_mixing,
    node_heterogeneity_summary,
    node_params_from_csv,
    node_sis_force,
    node_sis_jacobian,
    node_sis_rhs,
    resolve_degree_sis_params,
    resolve_node_sis_params,
    resolve_vector,
    seeded_lognormal_degree_params,
    summarize_vector,
)
from .io import require_outputs, set_seed, write_csv, write_json
from .plotting import (
    GUIDE_DPI,
    IEEE_DOUBLE_COLUMN_IN,
    IEEE_SINGLE_COLUMN_IN,
    PUBLICATION_COLORS,
    PUBLICATION_DPI,
    PUBLICATION_LINESTYLES,
    PUBLICATION_MARKERS,
    add_arrow,
    add_box,
    apply_clean_axes,
    clean_axes,
    figure_size,
    guide_style,
    panel_label,
    plot_time_series,
    publication_style,
    save_guide_figure,
    save_publication_figure,
    style_axis,
)
from .diagnostics import (
    COMMON_DIAGNOSTIC_TERMS,
    DiagnosticTerm,
    add_caption,
    diagnostic_terms_for,
    rolling_mean,
    write_diagnostic_glossary,
)

__all__ = [
    "HybridParams",
    "MalwareParams",
    "controlled_sir_rhs",
    "hybrid_rhs",
    "isolation_jump",
    "NodeSIPSParams",
    "contiguous_community_index",
    "DegreeSISParams",
    "NodeSISParams",
    "COMMON_DIAGNOSTIC_TERMS",
    "DiagnosticTerm",
    "GUIDE_DPI",
    "IEEE_DOUBLE_COLUMN_IN",
    "IEEE_SINGLE_COLUMN_IN",
    "PUBLICATION_COLORS",
    "PUBLICATION_DPI",
    "PUBLICATION_LINESTYLES",
    "PUBLICATION_MARKERS",
    "add_arrow",
    "add_box",
    "add_caption",
    "apply_clean_axes",
    "as_time_function",
    "clean_axes",
    "diagnostic_terms_for",
    "assortative_degree_mixing",
    "community_correlated_node_sips_params",
    "degree_correlated_node_sips_params",
    "degree_correlated_node_sis_params",
    "degree_correlated_sis_params",
    "degree_sis_force",
    "degree_sis_jacobian",
    "degree_sis_rhs",
    "figure_size",
    "finite_difference_jacobian",
    "guide_style",
    "homogeneous_node_sips_params",
    "neutral_degree_mixing",
    "node_heterogeneity_summary",
    "node_params_from_csv",
    "node_sis_force",
    "node_sis_jacobian",
    "node_sis_rhs",
    "panel_label",
    "plot_time_series",
    "project_box",
    "project_compartments",
    "project_simplex",
    "project_simplex3",
    "ResolvedDegreeSISParams",
    "ResolvedNodeSISParams",
    "ResolvedNodeSIPSParams",
    "resolve_degree_sis_params",
    "resolve_node_sis_params",
    "resolve_vector",
    "require_outputs",
    "rk4_integrate",
    "rk4_step",
    "rolling_mean",
    "publication_style",
    "set_seed",
    "save_guide_figure",
    "save_publication_figure",
    "graph_pressure_numpy",
    "graph_pressure_torch",
    "node_sips_rhs_numpy",
    "node_sips_rhs_torch",
    "node_sips_transition_rates",
    "normalize_adjacency",
    "solve_ode_grid",
    "sample_node_sips_step",
    "seeded_lognormal_degree_params",
    "seeded_lognormal_node_sips_params",
    "style_axis",
    "summarize_vector",
    "trapezoid",
    "trapezoid_integral",
    "write_csv",
    "write_diagnostic_glossary",
    "write_json",
]
