# Copyright (c) 2026 Lu-Xing Yang.
# No project-wide open-source license is granted; see repository COPYRIGHT_AND_LICENSE.md.

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
os.environ.setdefault("MPLCONFIGDIR", str((HERE / ".mplconfig").resolve()))
os.environ.setdefault("XDG_CACHE_HOME", str((HERE / ".cache").resolve()))
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)
Path(os.environ["XDG_CACHE_HOME"]).mkdir(parents=True, exist_ok=True)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def run(cmd: list[str], env: dict[str, str]) -> None:
    print("$ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=HERE, env=env, check=True)


def require_outputs(paths: list[Path]) -> None:
    missing = [path for path in paths if not path.exists()]
    empty = [path for path in paths if path.exists() and path.stat().st_size == 0]
    if missing or empty:
        details = []
        if missing:
            details.append("missing: " + ", ".join(str(path) for path in missing))
        if empty:
            details.append("empty: " + ", ".join(str(path) for path in empty))
        raise RuntimeError("Expected output check failed; " + "; ".join(details))


def make_contact_sheet(items: list[tuple[str, Path]], out_path: Path, cols: int = 3) -> None:
    require_outputs([path for _, path in items])
    rows = (len(items) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(4.8 * cols, 3.5 * rows))
    flat_axes = axes.ravel() if hasattr(axes, "ravel") else [axes]

    for ax, (title, path) in zip(flat_axes, items):
        ax.imshow(plt.imread(path))
        ax.set_title(title)
        ax.axis("off")

    for ax in flat_axes[len(items):]:
        ax.axis("off")

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def write_figure_explanations(out: Path) -> None:
    text = """# Lecture Example Figure Explanations

This file is generated by `run_all_lecture_examples.py` for the current run.

## How to read the x-axes

- `degree k`: the graph degree class. These plots check whether the input graph was loaded and aggregated correctly.
- `time`: the simulated model time. These plots show how the system state and the computed control or game strategies evolve.
- Continuous controls or strategies: time-indexed curves sampled on the simulation grid. Projected controls can have flat bound segments, and the generated examples use line styles and parameter choices that make their time variation visible.
- Impulse controls: vertical event lines at discrete intervention times. They are not connected continuous curves.
- Hybrid control: a combination of continuous control and impulse interventions. State trajectories may jump at impulse times.
- State labels specify the aggregation level: node mean over all nodes, degree-weighted mean over degree classes, or a selected degree class `k`.

## Generated outputs

| Output pattern | X-axis | What it shows | Interpretation |
| --- | --- | --- | --- |
| `*/degree_distribution.png` | degree `k` | Empirical degree distribution `P(k)` | Smoke check for graph loading and degree aggregation. |
| `simple_*/degree_k_control.png` | time | Degree-weighted mean infection/control and selected degree-class states | Degree-k continuous optimal-control trajectory produced by the forward-backward sweep. |
| `examples_*/degree_control.png` | time | Degree-level infection and continuous control | State evolution under the computed continuous optimal control. |
| `examples_*/degree_game.png` | time | Degree-level infection plus continuous attack/defense strategies | Open-loop continuous attacker-defender game trajectory under computed strategies. |
| `examples_*/node_control.png` | time | Node-level mean/max infection and node-mean continuous control | Node-level continuous optimal-control trajectory on the reduced graph. |
| `examples_*/node_game.png` | time | Node-mean infection plus continuous attack/defense strategies | Node-level continuous differential-game trajectory under computed strategies. |
| `examples_*/hybrid_impulse.png` | time | Node-level states, continuous control, and impulse magnitudes | Hybrid simulation with continuous dynamics in the top panel and continuous/discrete control types separated in the bottom panel. |
| `*/fbs_convergence.png` | iteration | Maximum control/strategy change per forward-backward sweep step | Convergence diagnostic; the curve should decrease toward the stated tolerance. |
| `simple_*/baseline_comparison.png` | scenario | Computed degree-k control vs deterministic and random controls | Single-model sanity check against no-control, constant-control, and random smooth-control baselines. |
| `examples_*/*_control_baseline_comparison.png` | scenario | One continuous-control model per figure | Computed control is compared with no-control, constant-control, and random smooth-control baselines. |
| `examples_*/*_game_baseline_comparison.png` | scenario | One differential game per figure, with two unilateral panels | One panel fixes the computed attack and varies defense; the other fixes the computed defense and varies attack. Random baselines show whether the computed player strategy is competitive. |
| `simple_contact_sheet.png` | mixed | Overview of simple degree-k runs | Visual index for the three simple smoke cases. |
| `examples_contact_sheet.png` | mixed | Overview of companion examples | Visual index for degree, node, and hybrid smoke cases. |

The purpose of these runs is not full paper-scale reproduction. They are small, fast checks that the model-loading, state dynamics, adjoint/control update, plotting, and file-output paths all work.
"""
    (out / "figure_explanations.md").write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run all lecture-package optimal-control/differential-game examples.")
    parser.add_argument(
        "--output-root",
        type=Path,
        default=HERE / "results" / ("rerun_" + datetime.now().strftime("%Y%m%d_%H%M%S")),
        help="Directory where rerun outputs will be written.",
    )
    parser.add_argument("--steps", type=int, default=45, help="Time-grid size for companion examples.")
    args = parser.parse_args()

    out = args.output_root.resolve()
    out.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env.setdefault("MPLCONFIGDIR", str((HERE / ".mplconfig").resolve()))
    env.setdefault("XDG_CACHE_HOME", str((HERE / ".cache").resolve()))
    Path(env["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)
    Path(env["XDG_CACHE_HOME"]).mkdir(parents=True, exist_ok=True)

    py = sys.executable
    simple = HERE / "code" / "simple_degree_k_control.py"
    examples = HERE / "code" / "network_control_examples.py"

    run([py, str(simple), "--output-dir", str(out / "simple_demo")], env)
    run([
        py, str(simple),
        "--edge-list", str(HERE / "sample_data" / "sample_edges.csv"),
        "--delimiter", ",",
        "--has-header",
        "--source-col", "source",
        "--target-col", "target",
        "--output-dir", str(out / "simple_edges"),
    ], env)
    run([
        py, str(simple),
        "--adjacency-csv", str(HERE / "sample_data" / "sample_adjacency.csv"),
        "--output-dir", str(out / "simple_adjacency"),
    ], env)

    run([py, str(examples), "--steps", str(args.steps), "--output-dir", str(out / "examples_demo")], env)
    run([
        py, str(examples),
        "--edge-list", str(HERE / "sample_data" / "sample_edges.csv"),
        "--delimiter", ",",
        "--has-header",
        "--source-col", "source",
        "--target-col", "target",
        "--steps", str(args.steps),
        "--output-dir", str(out / "examples_edges"),
    ], env)
    run([
        py, str(examples),
        "--adjacency-csv", str(HERE / "sample_data" / "sample_adjacency.csv"),
        "--steps", str(args.steps),
        "--output-dir", str(out / "examples_adjacency"),
    ], env)

    simple_items = [
        ("simple demo: degree", out / "simple_demo" / "degree_distribution.png"),
        ("simple demo: control", out / "simple_demo" / "degree_k_control.png"),
        ("simple demo: FBS", out / "simple_demo" / "fbs_convergence.png"),
        ("simple demo: baseline", out / "simple_demo" / "baseline_comparison.png"),
        ("simple edge: degree", out / "simple_edges" / "degree_distribution.png"),
        ("simple edge: control", out / "simple_edges" / "degree_k_control.png"),
        ("simple edge: FBS", out / "simple_edges" / "fbs_convergence.png"),
        ("simple edge: baseline", out / "simple_edges" / "baseline_comparison.png"),
        ("simple adjacency: degree", out / "simple_adjacency" / "degree_distribution.png"),
        ("simple adjacency: control", out / "simple_adjacency" / "degree_k_control.png"),
        ("simple adjacency: FBS", out / "simple_adjacency" / "fbs_convergence.png"),
        ("simple adjacency: baseline", out / "simple_adjacency" / "baseline_comparison.png"),
    ]
    example_items = [
        ("demo: degree", out / "examples_demo" / "degree_distribution.png"),
        ("demo: control", out / "examples_demo" / "degree_control.png"),
        ("demo: game", out / "examples_demo" / "degree_game.png"),
        ("demo: node control", out / "examples_demo" / "node_control.png"),
        ("demo: node game", out / "examples_demo" / "node_game.png"),
        ("demo: hybrid", out / "examples_demo" / "hybrid_impulse.png"),
        ("demo: FBS", out / "examples_demo" / "fbs_convergence.png"),
        ("demo: degree ctl baseline", out / "examples_demo" / "degree_control_baseline_comparison.png"),
        ("demo: degree game baseline", out / "examples_demo" / "degree_game_baseline_comparison.png"),
        ("demo: node ctl baseline", out / "examples_demo" / "node_control_baseline_comparison.png"),
        ("demo: node game baseline", out / "examples_demo" / "node_game_baseline_comparison.png"),
        ("edge: degree", out / "examples_edges" / "degree_distribution.png"),
        ("edge: control", out / "examples_edges" / "degree_control.png"),
        ("edge: game", out / "examples_edges" / "degree_game.png"),
        ("edge: node control", out / "examples_edges" / "node_control.png"),
        ("edge: node game", out / "examples_edges" / "node_game.png"),
        ("edge: FBS", out / "examples_edges" / "fbs_convergence.png"),
        ("edge: degree ctl baseline", out / "examples_edges" / "degree_control_baseline_comparison.png"),
        ("edge: degree game baseline", out / "examples_edges" / "degree_game_baseline_comparison.png"),
        ("edge: node ctl baseline", out / "examples_edges" / "node_control_baseline_comparison.png"),
        ("edge: node game baseline", out / "examples_edges" / "node_game_baseline_comparison.png"),
        ("adjacency: degree", out / "examples_adjacency" / "degree_distribution.png"),
        ("adjacency: control", out / "examples_adjacency" / "degree_control.png"),
        ("adjacency: game", out / "examples_adjacency" / "degree_game.png"),
        ("adjacency: node control", out / "examples_adjacency" / "node_control.png"),
        ("adjacency: node game", out / "examples_adjacency" / "node_game.png"),
        ("adjacency: FBS", out / "examples_adjacency" / "fbs_convergence.png"),
        ("adjacency: degree ctl baseline", out / "examples_adjacency" / "degree_control_baseline_comparison.png"),
        ("adjacency: degree game baseline", out / "examples_adjacency" / "degree_game_baseline_comparison.png"),
        ("adjacency: node ctl baseline", out / "examples_adjacency" / "node_control_baseline_comparison.png"),
        ("adjacency: node game baseline", out / "examples_adjacency" / "node_game_baseline_comparison.png"),
    ]

    csv_outputs = [
        out / name / "degree_distribution.csv"
        for name in (
            "simple_demo",
            "simple_edges",
            "simple_adjacency",
            "examples_demo",
            "examples_edges",
            "examples_adjacency",
        )
    ]
    csv_outputs.extend(
        out / name / file_name
        for name in (
            "simple_demo",
            "simple_edges",
            "simple_adjacency",
            "examples_demo",
            "examples_edges",
            "examples_adjacency",
        )
        for file_name in ("fbs_convergence.csv", "baseline_summary.csv")
    )
    require_outputs([path for _, path in simple_items + example_items] + csv_outputs)

    make_contact_sheet(simple_items, out / "simple_contact_sheet.png")
    make_contact_sheet(example_items, out / "examples_contact_sheet.png", cols=4)
    write_figure_explanations(out)
    require_outputs([
        out / "simple_contact_sheet.png",
        out / "examples_contact_sheet.png",
        out / "figure_explanations.md",
    ])

    print(f"\nDone. Outputs written to: {out}")


if __name__ == "__main__":
    main()
