# Copyright (c) 2026 Lu-Xing Yang.
# No project-wide open-source license is granted; see repository COPYRIGHT_AND_LICENSE.md.

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
ROOT_DIR = HERE.parents[1]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

os.environ.setdefault("MPLCONFIGDIR", str((HERE / ".mplconfig").resolve()))
os.environ.setdefault("XDG_CACHE_HOME", str((HERE / ".cache").resolve()))
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)
Path(os.environ["XDG_CACHE_HOME"]).mkdir(parents=True, exist_ok=True)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from cybercontrol.io import require_outputs


def run(cmd: list[str], env: dict[str, str]) -> None:
    print("$ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=HERE, env=env, check=True)


def make_contact_sheet(items: list[tuple[str, Path]], out_path: Path, cols: int = 3) -> None:
    require_outputs([path for _, path in items])
    rows = (len(items) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(4.8 * cols, 3.5 * rows))
    flat_axes = axes.ravel() if hasattr(axes, "ravel") else [axes]

    for ax, (title, path) in zip(flat_axes, items):
        ax.imshow(plt.imread(path))
        ax.set_title(title)
        ax.axis("off")

    for ax in flat_axes[len(items):]:
        ax.axis("off")

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def parse_size_values(raw: str) -> list[int]:
    return [int(item.strip()) for item in raw.split(",") if item.strip()]


def scalability_plot_name(model_level: str, sizes: list[int]) -> str:
    return f"{model_level}_control_scalability_{min(sizes)}_{max(sizes)}.png"


def write_results_readme(
    out: Path,
    *,
    include_scalability: bool,
    scalability_plot: str | None,
    include_node_scalability: bool,
    node_scalability_plot: str | None,
) -> None:
    scalability_axis = ""
    scalability_guide_row = ""
    scalability_index_row = ""
    if include_scalability:
        scalability_axis = "- `network size`: the number of nodes in a synthetic scale-free network used for scalability timing.\n"
        scalability_guide_row = (
            f"| `scalability_degree_sf/{scalability_plot}` | network size | Degree-level adaptive FBS runtime on "
            "synthetic scale-free networks | Runtime trend from 100 to 2000 nodes, with repeat-to-repeat variation "
            "and convergence diagnostics. |\n"
        )
        scalability_index_row = (
            f"| Scalability | `scalability_degree_sf/` | How does degree-level FBS runtime change from 100 to 2000 "
            f"synthetic SF nodes? | `{scalability_plot}` |\n"
        )
    node_scalability_guide_row = ""
    node_scalability_index_row = ""
    if include_node_scalability:
        node_scalability_guide_row = (
            f"| `scalability_node_sf/{node_scalability_plot}` | network size | Sparse fixed-grid node-level FBS runtime on "
            "synthetic scale-free networks | Runtime and convergence trend from 1000 to 10000 node-indexed states; compare only with the solver type in view. |\n"
        )
        node_scalability_index_row = (
            f"| Node-level scalability | `scalability_node_sf/` | How does sparse node-level FBS behave from 1000 "
            f"to 10000 nodes? | `{node_scalability_plot}` |\n"
        )

    text = f"""# Foundation Example Results

This file is generated by `run_foundation_examples.py` for the current run.

## Run Map

| Category | Output folder | Question answered | Key figure |
| --- | --- | --- | --- |
| Simple degree-k control | `simple_builtin_sf/` | Does the minimal degree-level FBS optimal-control example run on a built-in scale-free network? | `degree_control_trajectory.png` |
| Simple degree-k control | `simple_sample_edges/` | Does the same minimal model run on a sample edge list? | `degree_control_trajectory.png` |
| Simple degree-k control | `simple_sample_adjacency/` | Does the same minimal model run on a sample adjacency matrix? | `degree_control_trajectory.png` |
| Companion models | `companion_builtin_sf/` | How do degree-level, node-level, game, and hybrid examples compare on a built-in scale-free network? | `degree_control_trajectory.png`, `degree_game_trajectory.png`, `hybrid_impulse_trajectory.png` |
| Companion models | `companion_sample_edges/` | Do the companion models run from the sample edge list? | `node_control_trajectory.png` |
| Companion models | `companion_sample_adjacency/` | Do the companion models run from the sample adjacency matrix? | `node_game_trajectory.png` |
{scalability_index_row.rstrip()}
{node_scalability_index_row.rstrip()}

## How To Read The X-Axes

- `degree k`: the graph degree class. These plots check whether the input graph was loaded and aggregated correctly.
- `time`: the simulated model time. These plots show how the system state and the computed control or game strategies evolve.
{scalability_axis.rstrip()}
- Continuous controls or strategies: time-indexed curves sampled on the simulation grid. Projected controls can have flat bound segments, and the generated examples use line styles and parameter choices that make their time variation visible.
- Impulse controls: vertical event lines at discrete intervention times. They are not connected continuous curves.
- Hybrid control: a combination of continuous control and impulse interventions. State trajectories may jump at impulse times.
- State labels specify the aggregation level: node mean over all nodes, population-weighted degree-class mean, or a selected degree class `k`.

## Parameter Quick Reference

Each `simple_*` and `companion_*` folder includes `parameter_summary.csv`.
Use it as the first stop for concrete values such as total time horizon, time-grid size, infection/contact rate `beta`, recovery rate `delta`, control or strategy bounds, impulse times, and random-baseline count. The values are small enough for smoke runs while still making continuous strategies and impulse effects visible in the figures.

## Figure Guide

| Output pattern | X-axis | What it shows | Interpretation |
| --- | --- | --- | --- |
| `*/degree_distribution.png` | degree `k` | Empirical degree distribution `P(k)` | Smoke check for graph loading and degree aggregation. |
| `simple_*/degree_control_trajectory.png` | time | Degree-weighted mean infection/control and selected degree-class states | Degree-k continuous optimal-control trajectory produced by the forward-backward sweep. |
| `companion_*/degree_control_trajectory.png` | time | Degree-level infection and continuous control | State evolution under the computed continuous optimal control. |
| `companion_*/degree_game_trajectory.png` | time | Degree-level infection plus continuous attack/defense strategies | Open-loop continuous attacker-defender game trajectory under computed strategies. |
| `companion_*/node_control_trajectory.png` | time | Node-level mean/max infection and node-mean continuous control | Node-level continuous optimal-control trajectory on the reduced graph. |
| `companion_*/node_game_trajectory.png` | time | Node-mean infection plus continuous attack/defense strategies | Node-level continuous differential-game trajectory under computed strategies. |
| `companion_*/hybrid_impulse_trajectory.png` | time | Node-level states, continuous control, and impulse magnitudes | Hybrid simulation with continuous dynamics in the top panel and continuous/discrete control types separated in the bottom panel. |
| `*/fbs_convergence.png` | iteration | Maximum control/strategy change per forward-backward sweep step | Convergence diagnostic; the curve should decrease toward the stated tolerance. |
| `simple_*/degree_control_baseline_comparison.png` | scenario | Computed degree-k control vs deterministic and random controls | Single-model sanity check against no-control, constant-control, and random smooth-control baselines. |
| `companion_*/*_control_baseline_comparison.png` | scenario | One continuous-control model per figure | Computed control is compared with no-control, constant-control, and random smooth-control baselines. |
| `companion_*/*_game_baseline_comparison.png` | scenario | One differential game per figure, with two unilateral panels | One panel fixes the computed attack and varies defense; the other fixes the computed defense and varies attack. Random baselines show whether the computed player strategy is competitive. |
{scalability_guide_row.rstrip()}
{node_scalability_guide_row.rstrip()}
| `*/parameter_summary.csv` | table | Concrete smoke-run parameter values | Time horizon, grid size, propagation/recovery rates, control bounds, impulse times, and random baseline count. |
| `simple_contact_sheet.png` | mixed | Overview of simple degree-k runs | Visual index for the three simple smoke cases. |
| `companion_contact_sheet.png` | mixed | Overview of companion examples | Visual index for degree, node, and hybrid smoke cases. |

The purpose of these runs is not full paper-scale reproduction. They are small, fast checks that the model-loading, state dynamics, adjoint/control update, plotting, and file-output paths all work.
"""
    (out / "README.md").write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run all foundation optimal-control/differential-game examples.")
    parser.add_argument(
        "--output-root",
        type=Path,
        default=HERE / "results" / ("rerun_" + datetime.now().strftime("%Y%m%d_%H%M%S")),
        help="Directory where rerun outputs will be written.",
    )
    parser.add_argument("--steps", type=int, default=45, help="Time-grid size for companion examples.")
    parser.add_argument("--skip-scalability", action="store_true", help="Skip the synthetic SF scalability run.")
    parser.add_argument(
        "--scalability-sizes",
        default=",".join(str(nodes) for nodes in range(100, 2001, 100)),
        help="Comma-separated node counts for scalability analysis.",
    )
    parser.add_argument("--scalability-repeats", type=int, default=3)
    parser.add_argument("--scalability-steps", type=int, default=35)
    parser.add_argument("--scalability-iterations", type=int, default=60)
    parser.add_argument(
        "--include-node-scalability",
        action="store_true",
        help="Also run the heavier sparse node-level FBS scalability experiment.",
    )
    parser.add_argument(
        "--node-scalability-sizes",
        default=",".join(str(nodes) for nodes in range(1000, 10001, 1000)),
        help="Comma-separated node counts for sparse node-level scalability.",
    )
    parser.add_argument("--node-scalability-repeats", type=int, default=1)
    parser.add_argument("--node-scalability-steps", type=int, default=25)
    parser.add_argument("--node-scalability-iterations", type=int, default=50)
    args = parser.parse_args()

    out = args.output_root.resolve()
    out.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env.setdefault("MPLCONFIGDIR", str((HERE / ".mplconfig").resolve()))
    env.setdefault("XDG_CACHE_HOME", str((HERE / ".cache").resolve()))
    Path(env["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)
    Path(env["XDG_CACHE_HOME"]).mkdir(parents=True, exist_ok=True)

    py = sys.executable
    simple = HERE / "code" / "simple_degree_k_control.py"
    examples = HERE / "code" / "network_control_examples.py"
    scalability = HERE / "code" / "scalability_analysis.py"

    simple_builtin = out / "simple_builtin_sf"
    simple_edges = out / "simple_sample_edges"
    simple_adjacency = out / "simple_sample_adjacency"
    companion_builtin = out / "companion_builtin_sf"
    companion_edges = out / "companion_sample_edges"
    companion_adjacency = out / "companion_sample_adjacency"
    scalability_dir = out / "scalability_degree_sf"
    node_scalability_dir = out / "scalability_node_sf"
    scalability_sizes = parse_size_values(args.scalability_sizes)
    scalability_plot = scalability_plot_name("degree", scalability_sizes)
    node_scalability_sizes = parse_size_values(args.node_scalability_sizes)
    node_scalability_plot = scalability_plot_name("node", node_scalability_sizes)

    for legacy_name in ("examples_contact_sheet.png", "experiment_index.md", "figure_explanations.md"):
        legacy_path = out / legacy_name
        if legacy_path.exists():
            legacy_path.unlink()

    run([py, str(simple), "--output-dir", str(simple_builtin)], env)
    run([
        py, str(simple),
        "--edge-list", str(HERE / "sample_data" / "sample_edges.csv"),
        "--delimiter", ",",
        "--has-header",
        "--source-col", "source",
        "--target-col", "target",
        "--output-dir", str(simple_edges),
    ], env)
    run([
        py, str(simple),
        "--adjacency-csv", str(HERE / "sample_data" / "sample_adjacency.csv"),
        "--output-dir", str(simple_adjacency),
    ], env)

    run([py, str(examples), "--steps", str(args.steps), "--output-dir", str(companion_builtin)], env)
    run([
        py, str(examples),
        "--edge-list", str(HERE / "sample_data" / "sample_edges.csv"),
        "--delimiter", ",",
        "--has-header",
        "--source-col", "source",
        "--target-col", "target",
        "--steps", str(args.steps),
        "--output-dir", str(companion_edges),
    ], env)
    run([
        py, str(examples),
        "--adjacency-csv", str(HERE / "sample_data" / "sample_adjacency.csv"),
        "--steps", str(args.steps),
        "--output-dir", str(companion_adjacency),
    ], env)

    if not args.skip_scalability:
        run([
            py,
            str(scalability),
            "--model-level",
            "degree",
            "--sizes",
            args.scalability_sizes,
            "--repeats",
            str(args.scalability_repeats),
            "--steps",
            str(args.scalability_steps),
            "--iterations",
            str(args.scalability_iterations),
            "--output-dir",
            str(scalability_dir),
        ], env)
    if args.include_node_scalability:
        run([
            py,
            str(scalability),
            "--model-level",
            "node",
            "--node-solver",
            "sparse",
            "--sizes",
            args.node_scalability_sizes,
            "--repeats",
            str(args.node_scalability_repeats),
            "--steps",
            str(args.node_scalability_steps),
            "--iterations",
            str(args.node_scalability_iterations),
            "--output-dir",
            str(node_scalability_dir),
        ], env)

    simple_items = [
        ("simple | built-in SF | degree", simple_builtin / "degree_distribution.png"),
        ("simple | built-in SF | trajectory", simple_builtin / "degree_control_trajectory.png"),
        ("simple | built-in SF | FBS", simple_builtin / "fbs_convergence.png"),
        ("simple | built-in SF | baseline", simple_builtin / "degree_control_baseline_comparison.png"),
        ("simple | edge list | degree", simple_edges / "degree_distribution.png"),
        ("simple | edge list | trajectory", simple_edges / "degree_control_trajectory.png"),
        ("simple | edge list | FBS", simple_edges / "fbs_convergence.png"),
        ("simple | edge list | baseline", simple_edges / "degree_control_baseline_comparison.png"),
        ("simple | adjacency | degree", simple_adjacency / "degree_distribution.png"),
        ("simple | adjacency | trajectory", simple_adjacency / "degree_control_trajectory.png"),
        ("simple | adjacency | FBS", simple_adjacency / "fbs_convergence.png"),
        ("simple | adjacency | baseline", simple_adjacency / "degree_control_baseline_comparison.png"),
    ]
    companion_items = [
        ("companion | built-in SF | degree", companion_builtin / "degree_distribution.png"),
        ("companion | built-in SF | degree control", companion_builtin / "degree_control_trajectory.png"),
        ("companion | built-in SF | degree game", companion_builtin / "degree_game_trajectory.png"),
        ("companion | built-in SF | node control", companion_builtin / "node_control_trajectory.png"),
        ("companion | built-in SF | node game", companion_builtin / "node_game_trajectory.png"),
        ("companion | built-in SF | hybrid", companion_builtin / "hybrid_impulse_trajectory.png"),
        ("companion | built-in SF | FBS", companion_builtin / "fbs_convergence.png"),
        ("companion | built-in SF | degree ctl baseline", companion_builtin / "degree_control_baseline_comparison.png"),
        ("companion | built-in SF | degree game baseline", companion_builtin / "degree_game_baseline_comparison.png"),
        ("companion | built-in SF | node ctl baseline", companion_builtin / "node_control_baseline_comparison.png"),
        ("companion | built-in SF | node game baseline", companion_builtin / "node_game_baseline_comparison.png"),
        ("companion | edge list | degree", companion_edges / "degree_distribution.png"),
        ("companion | edge list | degree control", companion_edges / "degree_control_trajectory.png"),
        ("companion | edge list | degree game", companion_edges / "degree_game_trajectory.png"),
        ("companion | edge list | node control", companion_edges / "node_control_trajectory.png"),
        ("companion | edge list | node game", companion_edges / "node_game_trajectory.png"),
        ("companion | edge list | FBS", companion_edges / "fbs_convergence.png"),
        ("companion | edge list | degree ctl baseline", companion_edges / "degree_control_baseline_comparison.png"),
        ("companion | edge list | degree game baseline", companion_edges / "degree_game_baseline_comparison.png"),
        ("companion | edge list | node ctl baseline", companion_edges / "node_control_baseline_comparison.png"),
        ("companion | edge list | node game baseline", companion_edges / "node_game_baseline_comparison.png"),
        ("companion | adjacency | degree", companion_adjacency / "degree_distribution.png"),
        ("companion | adjacency | degree control", companion_adjacency / "degree_control_trajectory.png"),
        ("companion | adjacency | degree game", companion_adjacency / "degree_game_trajectory.png"),
        ("companion | adjacency | node control", companion_adjacency / "node_control_trajectory.png"),
        ("companion | adjacency | node game", companion_adjacency / "node_game_trajectory.png"),
        ("companion | adjacency | FBS", companion_adjacency / "fbs_convergence.png"),
        ("companion | adjacency | degree ctl baseline", companion_adjacency / "degree_control_baseline_comparison.png"),
        ("companion | adjacency | degree game baseline", companion_adjacency / "degree_game_baseline_comparison.png"),
        ("companion | adjacency | node ctl baseline", companion_adjacency / "node_control_baseline_comparison.png"),
        ("companion | adjacency | node game baseline", companion_adjacency / "node_game_baseline_comparison.png"),
    ]
    companion_preview_items = [
        ("built-in SF | degree distribution", companion_builtin / "degree_distribution.png"),
        ("built-in SF | degree control", companion_builtin / "degree_control_trajectory.png"),
        ("built-in SF | degree game", companion_builtin / "degree_game_trajectory.png"),
        ("built-in SF | node control", companion_builtin / "node_control_trajectory.png"),
        ("built-in SF | node game", companion_builtin / "node_game_trajectory.png"),
        ("built-in SF | hybrid control", companion_builtin / "hybrid_impulse_trajectory.png"),
        ("built-in SF | FBS convergence", companion_builtin / "fbs_convergence.png"),
        ("built-in SF | game baseline", companion_builtin / "degree_game_baseline_comparison.png"),
    ]

    csv_outputs = [
        out / name / "degree_distribution.csv"
        for name in (
            "simple_builtin_sf",
            "simple_sample_edges",
            "simple_sample_adjacency",
            "companion_builtin_sf",
            "companion_sample_edges",
            "companion_sample_adjacency",
        )
    ]
    csv_outputs.extend(
        out / name / file_name
        for name in (
            "simple_builtin_sf",
            "simple_sample_edges",
            "simple_sample_adjacency",
            "companion_builtin_sf",
            "companion_sample_edges",
            "companion_sample_adjacency",
        )
        for file_name in ("fbs_convergence.csv", "baseline_summary.csv", "parameter_summary.csv")
    )
    scalability_outputs = []
    if not args.skip_scalability:
        scalability_outputs = [
            scalability_dir / "degree_control_scalability.csv",
            scalability_dir / "degree_control_scalability_summary.csv",
            scalability_dir / scalability_plot,
            scalability_dir / "scalability_summary.md",
        ]
    if args.include_node_scalability:
        scalability_outputs.extend([
            node_scalability_dir / "node_control_scalability.csv",
            node_scalability_dir / "node_control_scalability_summary.csv",
            node_scalability_dir / node_scalability_plot,
            node_scalability_dir / "scalability_summary.md",
        ])
    require_outputs([path for _, path in simple_items + companion_items] + csv_outputs + scalability_outputs)

    make_contact_sheet(simple_items, out / "simple_contact_sheet.png")
    make_contact_sheet(companion_preview_items, out / "companion_contact_sheet.png", cols=4)
    write_results_readme(
        out,
        include_scalability=not args.skip_scalability,
        scalability_plot=scalability_plot if not args.skip_scalability else None,
        include_node_scalability=args.include_node_scalability,
        node_scalability_plot=node_scalability_plot if args.include_node_scalability else None,
    )
    require_outputs([
        out / "simple_contact_sheet.png",
        out / "companion_contact_sheet.png",
        out / "README.md",
    ])

    print(f"\nDone. Outputs written to: {out}")


if __name__ == "__main__":
    main()
